### ISSUE TITLE
NameError: name 'candidate_trim5' is not defined

### ISSUE THREAD

**Issue by songxh1996** [davidliwei/mageck2-doc#1]
mageck2 count -l sam_human_library_annotated.txt -n 89 --sample-label "8,9" --fastq ERR376998.fastq.gz ERR376999.fastq.gz --trim-5 20
INFO  @ Thu, 23 Nov 2023 14:18:35: Parameters: /disk1/piyifei/.local/bin/mageck2 count -l sam_human_library_annotated.txt -n 89 --sample-label 8,9 --fastq ERR376998.fastq.gz ERR376999.fastq.gz --trim-5 20
INFO  @ Thu, 23 Nov 2023 14:18:35: Welcome to MAGeCK2 v0.1.0. Command: count
INFO  @ Thu, 23 Nov 2023 14:18:35: Header line of the library file detected; skip the first line ...
WARNING @ Thu, 23 Nov 2023 14:18:35: Duplicated sgRNA label ACACTTGTTTTCGGCTCCGC in line 43374. Skip this record.
INFO  @ Thu, 23 Nov 2023 14:18:35: Loading 23728 predefined sgRNAs.
WARNING @ Thu, 23 Nov 2023 14:18:35: There are 46568 sgRNAs with duplicated sequences.
INFO  @ Thu, 23 Nov 2023 14:18:35: Parsing FASTQ file ERR376998.fastq.gz...
INFO  @ Thu, 23 Nov 2023 14:18:35: Determining the trim-5 length of FASTQ file ERR376998.fastq.gz...
INFO  @ Thu, 23 Nov 2023 14:18:35: Possible gRNA lengths:12,9
Traceback (most recent call last):
  File "/disk1/piyifei/.local/bin/mageck2", line 56, in <module>
    main();
  File "/disk1/piyifei/.local/bin/mageck2", line 37, in main
    mageckcount_main(args);
  File "/disk1/piyifei/.local/lib/python3.7/site-packages/mageck2/mageckCount.py", line 772, in mageckcount_main
    (allmappeddict,datastat)=mageckcount_processfastq(args,genedict,sgdict,sgdict2=sgdict2)
  File "/disk1/piyifei/.local/lib/python3.7/site-packages/mageck2/mageckCount.py", line 524, in mageckcount_processfastq
    mageckcount_processonefile(filename,args,dict00,dict00_umi,sgdict,datastat[filename], pairedfile, adjust=adjust)
  File "/disk1/piyifei/.local/lib/python3.7/site-packages/mageck2/mageckCountIO.py", line 417, in mageckcount_processonefile
    (candidate_trim5,remainingseq_list)=mageckcount_trim5_auto(filename,args,genedict)
  File "/disk1/piyifei/.local/lib/python3.7/site-packages/mageck2/mageckCountIO.py", line 136, in mageckcount_trim5_auto
    logging.info('Specified trimming length:'+','.join([str(x) for x in candidate_trim5]))
NameError: name 'candidate_trim5' is not defined

**Comment by davidliwei** [comment]
Thanks for the report, and apologies for the long delay. This is now fixed in the **mageck2** code repository in davidliwei/mageck2#6.

The cause was a bug in `mageckcount_trim5_auto`: after parsing a numeric `--trim-5` value it logged an undefined variable (`candidate_trim5` instead of the parsed `trim_5_provided`), so any explicit `--trim-5` crashed with `NameError` before reading any reads. The fix is on `main`, and a regression test now covers the explicit `--trim-5` path in CI.

To get the fix, reinstall the latest version:

    pip install --force-reinstall git+https://github.com/davidliwei/mageck2.git

Note: this `mageck2-doc` repository is for documentation. For code bugs like this one, the [mageck2](https://github.com/davidliwei/mageck2/issues) repository is the right place to file in future. Closing as resolved — please reopen there if you still hit the issue.
